platform :ios, '11.4'
inhibit_all_warnings!

target 'todokmp' do
  use_frameworks!

  # Internal Dependencies
  pod 'TodoCommon',
    :path => '../iosframework/build/bin/iosUniversal/TodoCommonReleaseFramework'

end